tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli.sh
      source ./bin/generate_tf_cloud_login
      echo '' >>~/.bash_profile
      echo 'alias tf=terraform # Add Alias for Terraform' >>~/.bash_profile
      source ~/.bash_profile
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
      
  - name: aws-clicp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
      echo '' >>~/.bash_profile
      echo 'alias tf=terraform # Add Alias for Terraform' >>~/.bash_profile
      source ~/.bash_profile

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform